module.exports = (pageObject, header, mke, oai, name, sex, race, height, weight, hair, offense, dateWarrent, driversLicense, stateDL, expirationDateDL, plate, stateL, expirationDateL) => {
    pageObject
        .navigate('http://localhost:3000/#/enter')
        .click('@header')
        .setValue('@header', header)
        .click('@mke')
        .setValue('@mke', mke)
        .click('@oai')
        .setValue('@oai', oai)
        .click('@name')
        .setValue('@name', name)
        .click('select[name="sexInput"]')
        .click('option[value="F"]')
        .click('select[name="racInput"]')
        .click('option[value="W"]')
        // .click('@sex')
        // .setValue('@sex', sex)
        // .click('@race')
        // .setValue('@race', race)
        .click('@height')
        .setValue('@height', height)
        .click('@weight')
        .setValue('@weight', weight)
        .click('@hair')
        .setValue('@hair', hair)
        .click('@offense')
        .setValue('@offense', offense)
        .click('@dateWarrent')
        .setValue('@dateWarrent', dateWarrent)
        .click('@driversLicense')
        .setValue('@driversLicense', driversLicense)
        .click('@stateDL')
        .setValue('@stateDL', stateDL)
        .click('@expirationDateDL')
        .setValue('@expirationDateDL', expirationDateDL)
        //This doesn't accept future dates but should, will change for now to give valid answer
        .click('@plate')
        .setValue('@plate', plate)
        .click('@stateL')
        .setValue('@stateL', stateL)
        .click('@expirationDateL')
        .setValue('@expirationDateL', expirationDateL)
        .click('@saveButton'),
    pageObject.expect.element('@results').text.to.contain('Valid')
    pageObject.click('@clearButton')
}